# -*- coding: utf-8 -*-
"""machinelearning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pp1WeVBZLTbFW9HT8ZqQC2F51IKVtzbF
"""

#pelo longo?
#perna curta?
#faz auau?
porco1 = [0, 1, 0]
porco2 = [0, 1, 1]
porco3 = [1, 1, 0]

cachorro1 = [0, 1, 1]
cachorro2 = [1, 0, 1]
cachorro3 = [1, 1, 1]

treino_x = [porco1, porco2, porco3, cachorro1, cachorro2, cachorro3]
treino_y = [1, 1, 1, 0, 0, 0] # 0 cachorro 1 porco

from sklearn.svm import LinearSVC

modelo = LinearSVC()
modelo.fit(treino_x, treino_y)

animal_misterioso = [1, 1, 1]
modelo.predict([animal_misterioso]) # reposta da maquina: 0 - resposta correta, o animal é um cachorro

misterio1 = [1, 1, 1]
misterio2 = [1, 1, 0]
misterio3 = [0, 1, 1]

teste_x = [misterio1, misterio2, misterio3]
teste_y = [0, 1, 1]

previsoes = modelo.predict(teste_x)
previsoes # resposta da maquina: 0, 1, 0 - acertou os dois primeiros

from sklearn.metrics import accuracy_score
accuracy_score(teste_y, previsoes) # 0.6666666666666666 - 66% de taxa de acerto